// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class IOSConstants
{
        public const string achievement_entered_masters_club = "CgkIs4j8s8wCEAIQCA"; // <GPGSID>
        public const string achievement_first_10_game = "CgkIs4j8s8wCEAIQBQ"; // <GPGSID>
        public const string leaderboard_masters_club = "CgkIs4j8s8wCEAIQAg"; // <GPGSID>
        public const string leaderboard_ranking_points = "CgkIs4j8s8wCEAIQAQ"; // <GPGSID>
        public const string achievement_under_6_club = "CgkIs4j8s8wCEAIQCQ"; // <GPGSID>
        public const string achievement_played_50_games = "CgkIs4j8s8wCEAIQBg"; // <GPGSID>
        public const string BUNDLE_ID = "com.magiclampgames.NumberGame2"; // <GPGSID>
        public const string leaderboard_game_power = "CgkIs4j8s8wCEAIQAw"; // <GPGSID>
        public const string achievement_played_100_games = "CgkIs4j8s8wCEAIQBw"; // <GPGSID>
        public const string achievement_under_7_club = "CgkIs4j8s8wCEAIQCg"; // <GPGSID>

}

